trap1:
	python T2.py < trapezio1

trap2:
	python T2.py < trapezio2

trap3:
	python T2.py < trapezio3


simp1:
	python T2.py < simpson1


simp2:
	python T2.py < simpson2


romberg:
	python T2.py < romberg1


all:
	python T2.py < trapezio1 > saidas/st1
	python T2.py < trapezio2 > saidas/st2
	python T2.py < trapezio3 > saidas/st3
	python T2.py < romberg1  > saidas/sr1
	python T2.py < simpson2  > saidas/ss2
	python T2.py < simpson1  > saidas/ss1
