t1:
	python T3.py < teste1

t2:
	python T3.py < teste2

t3:
	python T3.py < teste3

t4:
	python T3.py < teste4

t5:
	python T3.py < teste5

t6:
	python T3.py < teste6

t7:
	python T3.py < teste7


all:
	python T3.py < teste1 > saidas/t1
	python T3.py < teste2 > saidas/t2
	python T3.py < teste3 > saidas/t3
	python T3.py < teste4 > saidas/t4
	python T3.py < teste5 > saidas/t5
	python T3.py < teste6 > saidas/t6
	python T3.py < teste7 > saidas/t7

